### ISSUE TITLE
Need help on creating List cells using data validation

### ISSUE THREAD

**Issue by BharathIO** [MathNya/umya-spreadsheet#178]
Hi,
  I am creating Excel with 2 sheets, One to create a List of values and the other to point values to display drop-down.

But calling `get_data_validations()` returns None. When I try to read validations from the existing Excel template and write to output a new file, my output workbook does not have any validations. Looks like they are not getting copied/cloned, could you please check and do the needful? I am attaching excel template for reference
  
<img width="1397" alt="Screenshot 2024-02-14 at 3 18 29 PM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/7b74a45d-c578-4f24-8408-1947ebf9f4c9">
<img width="735" alt="Screenshot 2024-02-14 at 3 21 12 PM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/118bca0c-65f7-425b-a9d6-e4ff49c5f886">

## Excel file
[lov-template.xlsx](https://github.com/MathNya/umya-spreadsheet/files/14277902/lov-template.xlsx)

**Comment by MathNya** [comment]
@BharathIO 
Thank you for contacting us.
We will address this in the next version of the software.

**Comment by BharathIO** [comment]
Thanks for the update @MathNya , may i know when can i expect next version with the above fixes?

**Comment by MathNya** [comment]
@BharathIO 
We will probably be able to release it around the end of this month.

**Comment by BharathIO** [comment]
Sure. I will be waiting for that feature. Hope it takes care of defined named ranges for Lists read/write.

**Comment by BharathIO** [comment]
I see we are facing issue when named range is creating like below.

`=OFFSET(LOV!$A$1,1,0,COUNTIF(LOV!$A:$A,"<>"&"")-1,1)`

**Comment by BharathIO** [comment]
Fyi, this is what i observed.

<img width="801" alt="Screenshot 2024-02-20 at 11 33 48 AM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/0104e847-5569-4396-9d78-7f805dc9ff4d">
<img width="261" alt="Screenshot 2024-02-20 at 11 31 34 AM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/e9bbfca7-b02e-4b7e-a85d-870a3498ff5d">

**Comment by MathNya** [comment]
@BharathIO 
We have released 1.2.1 which fixes this problem.
Please check it out.

**Comment by BharathIO** [comment]
I am still facing this issue after upgrading to 1.2.2. could you please check
## Output file
## [Employees (8).xlsx](https://github.com/MathNya/umya-spreadsheet/files/14432586/Employees.8.xlsx)


<img width="266" alt="Screenshot 2024-02-28 at 4 04 05 PM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/a0c90c30-f910-461d-adae-16fc8e800aec">

**Comment by BharathIO** [comment]
### Input file
## [lov-template-input.xlsx](https://github.com/MathNya/umya-spreadsheet/files/14432713/lov-template-input.xlsx)

### Output file 
## [1_lov_copy.xlsx](https://github.com/MathNya/umya-spreadsheet/files/14432718/1_lov_copy.xlsx)


``` rust
let template_path = "../lov-template-input.xlsx";
    let output_path = "../1_lov_copy.xlsx";
    let book = umya_spreadsheet::reader::xlsx::read(template_path).unwrap();

    let path = std::path::Path::new(output_path);
    let _ = umya_spreadsheet::writer::xlsx::write(&book, path);
    println!("File cloned successfully at: {}", output_path);
```

**Comment by BharathIO** [comment]
Hi @MathNya, did you get a chance to check above issue? Please correct if i am doing anything wrong

**Comment by MathNya** [comment]
@BharathIO 
Sorry for the delay in contacting you.
I will check the situation.

**Comment by MathNya** [comment]
@BharathIO 
We were able to correct the cause of the error.
Version 1.2.3 was released. Please check it out.

**Comment by BharathIO** [comment]
Thanks, @MathNya, it is working as expected now.

<img width="1037" alt="Screenshot 2024-03-01 at 4 27 10 PM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/6a695aed-d499-49f5-9300-5de0e64e0494">


<img width="898" alt="Screenshot 2024-03-01 at 4 27 25 PM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/bffeead3-8ba5-4b45-8bd6-e3f1dd024af5">
<img width="621" alt="Screenshot 2024-03-01 at 4 27 35 PM" src="https://github.com/MathNya/umya-spreadsheet/assets/15683929/cf0c210e-919b-4e09-8b58-acd3a05317df">


## Excel for reference

### [Employees (11).xlsx](https://github.com/MathNya/umya-spreadsheet/files/14460137/Employees.11.xlsx)
