### ISSUE TITLE
Charts corrupted after opening and saving .xlsx file

### ISSUE THREAD

**Issue by ROMA96x** [MathNya/umya-spreadsheet#281]
Hi Math,

first of all congratulation for the great project. 💯 

I am having an annoying issue when using umya-spreadshit to open, edit and then save an .xlsx file.
The original file has some charts.
When I run my script, I modify some cells in the file and then overwrite the file.

Trying to open the fail again, I get the following errors from Excel and the charts are not present anymore.

<img width="311" alt="Image" src="https://github.com/user-attachments/assets/6a586be3-33fb-4f8b-b26f-caaf49117f8e" />
<img width="503" alt="Image" src="https://github.com/user-attachments/assets/82eb8890-9a02-4932-8c3a-f4abbe5329fe" />

Do you know why this happen?
I would like to specify that the cells I am editing are not used in those charts.
I really don't get why the charts get corrupted.

Regards,
Marco

**Comment by MathNya** [comment]
@ROMA96x 
Thank you for contacting us.
Perhaps the content of the loaded file contains data structures that are not expected by umya-spreadsheet.
This is due to a lack of implementation in umya-spreadsheet.

If possible, please upload the file in which the error occurs.
We will analyze the cause.

**Comment by ROMA96x** [comment]
Hi Math,

this is a sample of the file with random data.

[file pulito - Copia.xlsx](https://github.com/user-attachments/files/20502958/file.pulito.-.Copia.xlsx)

As you can see, there are 2 sheets.  
Second sheets contains some charts.
If I open and save the file with umya-spreadsheet, the charts ends up being corrupted.

**Comment by ROMA96x** [comment]
@MathNya thank you! 😀

**Comment by MathNya** [comment]
Fixed a bug.
Please get the latest version.

**Comment by ROMA96x** [comment]
Hi @MathNya ,

thanks for the update! I just tested new version: now charts are not removed. 🥇 

Anyhow, I noticed that there is still an issue related to cell-comments.
These are still lost:
```
Removed records: Comments from part /xl/comments1.xml (Comments)
Removed records: Comments from part /xl/comments2.xml (Comments)
```

Do you prefer I open a new thread? Or we can use this one?

**Comment by MathNya** [comment]
@ROMA96x 
Thank you for confirming.
The error regarding comments is probably another glitch.
Please create a new Issue.
